In [2]:
import pandas as pd
grid_data = pd.read_csv(r"C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Multi Scale Energy Stress Analysis\data\ca_grid_dataset.csv")
grid_data.head()

,Unnamed: 0,Time,Season,Day_of_the_week,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand
0,0,2019-01-01-T00:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216
1,1,2019-01-01-T00:05,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106
2,2,2019-01-01-T00:10,1,1,0.0,0.0,0.0,2.88,56.194,1.78,0,2916,22130
3,3,2019-01-01-T00:15,1,1,0.0,0.0,0.0,2.88,56.344,1.74,0,2920,22040
4,4,2019-01-01-T00:20,1,1,0.0,0.0,0.0,2.84,56.440,1.72,0,2902,21963

In [3]:
grid_data.columns

Index(['Unnamed: 0', 'Time', 'Season', 'Day_of_the_week', 'DHI', 'DNI', 'GHI',
       'Wind_speed', 'Humidity', 'Temperature', 'PV_production',
       'Wind_production', 'Electric_demand'],
      dtype='object')

In [4]:
if 'Unnamed: 0' in grid_data.columns:
    grid_data = grid_data.drop(columns=['Unnamed: 0'])

In [5]:
#Separate Date and Time
grid_data['Time'] = pd.to_datetime(grid_data['Time'], format='%Y-%m-%d-T%H:%M')
grid_data['Date'] = grid_data['Time'].dt.date
grid_data['Clock_Time'] = grid_data['Time'].dt.time

In [6]:
grid_data.head(2)

,Time,Season,Day_of_the_week,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand,Date,Clock_Time
0,2019-01-01 00:00:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216,2019-01-01,00:00:00
1,2019-01-01 00:05:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106,2019-01-01,00:05:00

In [7]:
season_map = {1: 'Winter', 2: 'Spring', 3: 'Summer', 4: 'Autumn'}
grid_data['Season_Name'] = grid_data['Season'].map(season_map)
grid_data['Day_Name'] = grid_data['Time'].dt.day_name()
grid_data = grid_data.drop(columns=['Day_of_the_week'], errors='ignore')

In [8]:
grid_data.head(3)

,Time,Season,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand,Date,Clock_Time,Season_Name,Day_Name
0,2019-01-01 00:00:00,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216,2019-01-01,00:00:00,Winter,Tuesday
1,2019-01-01 00:05:00,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106,2019-01-01,00:05:00,Winter,Tuesday
2,2019-01-01 00:10:00,1,0.0,0.0,0.0,2.88,56.194,1.78,0,2916,22130,2019-01-01,00:10:00,Winter,Tuesday

In [9]:
#Renaming columns
new_names = {
    'Time': 'timestamp',
    'Date': 'date',
    'Clock_Time': 'clock_time',
    'Season_Name': 'season',
    'Day_Name': 'day_of_week',
    'DHI': 'dhi_w_per_m2',
    'DNI': 'dni_w_per_m2',
    'GHI': 'ghi_w_per_m2',
    'Wind_speed': 'wind_speed_ms',
    'Humidity': 'humidity_pct',
    'Temperature': 'temp_c',
    'PV_production': 'solar_energy_generation_mw',
    'Wind_production': 'wind_energy_generation_mw',
    'Electric_demand': 'electric_demand_mw'
}

grid_data = grid_data.rename(columns=new_names)

ordered_cols = [
    'timestamp', 'date', 'clock_time', 'season', 'day_of_week', 
    'temp_c', 'humidity_pct', 'wind_speed_ms', 'ghi_w_per_m2', 'dni_w_per_m2', 'dhi_w_per_m2',
    'solar_energy_generation_mw', 'wind_energy_generation_mw', 'electric_demand_mw'
]

grid_data = grid_data[ordered_cols]

In [10]:
grid_data.head(3)

,timestamp,date,clock_time,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_w_per_m2,dni_w_per_m2,dhi_w_per_m2,solar_energy_generation_mw,wind_energy_generation_mw,electric_demand_mw
0,2019-01-01 00:00:00,2019-01-01,00:00:00,Winter,Tuesday,1.82,56.036,2.88,0.0,0.0,0.0,0,2810,22216
1,2019-01-01 00:05:00,2019-01-01,00:05:00,Winter,Tuesday,1.82,56.036,2.88,0.0,0.0,0.0,0,2862,22106
2,2019-01-01 00:10:00,2019-01-01,00:10:00,Winter,Tuesday,1.78,56.194,2.88,0.0,0.0,0.0,0,2916,22130

In [12]:
#Data Validation
print("Missing values per column:")
print(grid_data.isnull().sum())

Missing values per column:
timestamp                     0
date                          0
clock_time                    0
season                        0
day_of_week                   0
temp_c                        0
humidity_pct                  0
wind_speed_ms                 0
ghi_w_per_m2                  0
dni_w_per_m2                  0
dhi_w_per_m2                  0
solar_energy_generation_mw    0
wind_energy_generation_mw     0
electric_demand_mw            0
dtype: int64

In [ ]:
# Check for negatives
negatives = (grid_data[['solar_energy_generation_mw', 'wind_energy_generation_mw', 'electric_demand_mw']] < 0).sum()
print("Negative values found:\n", negatives)

Negative values found:
 solar_energy_generation_mw    112829
wind_energy_generation_mw        216
electric_demand_mw                 0
dtype: int64

In [21]:
# Check when these negatives happen
neg_solar_hours = grid_data[grid_data['solar_energy_generation_mw'] < 0]['clock_time'].value_counts()
print("Hours where solar is negative:")
print(neg_solar_hours)

Hours where solar is negative:
clock_time
05:40:00    338
05:45:00    331
05:35:00    329
05:50:00    315
05:30:00    307
06:00:00    303
05:55:00    302
06:05:00    301
06:10:00    292
05:25:00    287
06:15:00    282
05:20:00    265
06:20:00    264
06:25:00    246
05:15:00    244
06:30:00    227
05:10:00    222
05:05:00    201
06:35:00    193
05:00:00    179
06:40:00    168
04:55:00    155
06:45:00    147
04:50:00    129
06:50:00    118
04:45:00     98
06:55:00     86
07:00:00     78
04:40:00     56
07:05:00     42
16:40:00     30
16:45:00     19
07:10:00     17
17:40:00     14
17:35:00     12
16:35:00     11
17:45:00     10
17:30:00      9
18:05:00      8
18:00:00      8
17:55:00      8
17:50:00      7
16:55:00      6
17:05:00      6
16:50:00      5
17:10:00      5
07:15:00      5
17:15:00      5
16:30:00      4
18:10:00      3
17:20:00      3
16:25:00      2
17:00:00      2
17:25:00      2
16:20:00      1
Name: count, dtype: int64

In [22]:
print("\nSummary of negative solar values:")
print(grid_data[grid_data['solar_energy_generation_mw'] < 0]['solar_energy_generation_mw'].describe())

Summary of negative solar values:
count    6707.000000
mean      -34.162964
std        11.740413
min       -75.000000
25%       -42.000000
50%       -39.000000
75%       -28.000000
max        -1.000000
Name: solar_energy_generation_mw, dtype: float64

In [ ]:
# Dealing with negatives
grid_data['sun_is_up'] = grid_data['ghi_w_per_m2'] > 5

night_mask = (grid_data['sun_is_up'] == False) & (grid_data['solar_energy_generation_mw'] < 0)
day_mask = (grid_data['sun_is_up'] == True) & (grid_data['solar_energy_generation_mw'] < 0)

grid_data.loc[night_mask, 'solar_energy_generation_mw'] = 0
grid_data.loc[day_mask, 'solar_energy_generation_mw'] = grid_data.loc[day_mask, 'solar_energy_generation_mw'].abs()

grid_data['solar_energy_generation_mw'] = grid_data['solar_energy_generation_mw'].clip(lower=0)

print(f"Fixed {night_mask.sum()} night-time rows to zero.")
print(f"Fixed {day_mask.sum()} day-time rows using modulus.")

Fixed 766 night-time rows to zero.
Fixed 5941 day-time rows using modulus.

In [ ]:
# Dealing with wind negatives
grid_data['wind_is_blowing'] = grid_data['wind_speed_ms'] > 2.5

wind_noise_mask = (grid_data['wind_is_blowing'] == False) & (grid_data['wind_energy_generation_mw'] < 0)
wind_sign_error_mask = (grid_data['wind_is_blowing'] == True) & (grid_data['wind_energy_generation_mw'] < 0)

grid_data.loc[wind_noise_mask, 'wind_energy_generation_mw'] = 0
grid_data.loc[wind_sign_error_mask, 'wind_energy_generation_mw'] = grid_data.loc[wind_sign_error_mask, 'wind_energy_generation_mw'].abs()

grid_data['wind_energy_generation_mw'] = grid_data['wind_energy_generation_mw'].clip(lower=0)

print(f"Fixed {wind_noise_mask.sum()} low-wind noise rows.")
print(f"Fixed {wind_sign_error_mask.sum()} wind sign-error rows.")

Fixed 110 low-wind noise rows.
Fixed 106 wind sign-error rows.

In [14]:
# Check for temperature outliers 
temp_outliers = grid_data[(grid_data['temp_c'] < -10) | (grid_data['temp_c'] > 55)]
print(f"Strange temperature rows: {len(temp_outliers)}")

Strange temperature rows: 0

In [16]:
# Force solar to zero at night (when GHI is 0)
grid_data.loc[grid_data['ghi_w_per_m2'] <= 0, 'solar_energy_generation_mw'] = 0

In [17]:
# Check if every day has 288 rows (12 rows/hr * 24 hrs)
counts = grid_data.groupby('date').size()
incomplete_days = counts[counts != 288]
print("Days with missing 5-minute intervals:\n", incomplete_days)

Days with missing 5-minute intervals:
 Series([], dtype: int64)

In [27]:
print(grid_data[grid_data['sun_is_up'] == True]['solar_energy_generation_mw'].max())

13191

In [ ]:
# 'Real' solar data left
active_solar_count = (grid_data['solar_energy_generation_mw'] > 0).sum()
total_rows = len(grid_data)
percentage_active = (active_solar_count / total_rows) * 100

print(f"Rows with active solar production: {active_solar_count}")
print(f"Percentage of total data: {percentage_active:.2f}%")

Rows with active solar production: 160626
Percentage of total data: 50.89%

In [30]:
# Resampling to Hourly

if grid_data.index.name != 'timestamp':
    grid_data = grid_data.set_index('timestamp')

# Create the complete hourly dataset
grid_hourly = grid_data.resample('H').agg({
    'date': 'first',
    'clock_time': 'first',
    'season': 'first',      
    'day_of_week': 'first',
    'temp_c': 'mean',
    'humidity_pct': 'mean',
    'wind_speed_ms': 'mean',
    'ghi_w_per_m2': 'mean',
    'dni_w_per_m2': 'mean',
    'dhi_w_per_m2': 'mean',
    'solar_energy_generation_mw': 'mean',
    'wind_energy_generation_mw': 'mean',
    'electric_demand_mw': ['mean', 'max', 'std'] # Keep the 'spikiness' metrics
}).copy()

grid_hourly.columns = [
    'date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct', 'wind_speed_ms', 
    'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw', 'wind_gen_mw', 
    'demand_avg_mw', 'demand_max_mw', 'demand_std_mw'
]

# Calculate Net Load
grid_hourly['net_load_mw'] = grid_hourly['demand_avg_mw'] - grid_hourly['solar_gen_mw'] - grid_hourly['wind_gen_mw']

C:\Users\Hp\AppData\Local\Temp\ipykernel_2764\1000948811.py:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  grid_hourly = grid_data.resample('H').agg({

In [31]:
grid_hourly.head(10)

,date,clock_time,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_wm2,dni_wm2,dhi_wm2,solar_gen_mw,wind_gen_mw,demand_avg_mw,demand_max_mw,demand_std_mw,net_load_mw
timestamp,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,2019-01-01,00:00:00,Winter,Tuesday,1.683333,55.809333,2.838333,0.000000,0.000000,0.000000,0.000000,2812.083333,21851.416667,22216,237.839693,19039.333333
2019-01-01 01:00:00,2019-01-01,01:00:00,Winter,Tuesday,1.405000,55.159000,2.770000,0.000000,0.000000,0.000000,0.000000,2499.500000,21099.666667,21435,213.642153,18600.166667
2019-01-01 02:00:00,2019-01-01,02:00:00,Winter,Tuesday,1.186667,54.532833,2.690000,0.000000,0.000000,0.000000,0.000000,2387.083333,20495.416667,20724,137.656660,18108.333333
2019-01-01 03:00:00,2019-01-01,03:00:00,Winter,Tuesday,0.985000,54.317833,2.655000,0.000000,0.000000,0.000000,0.000000,2369.333333,20147.500000,20280,75.523025,17778.166667
2019-01-01 04:00:00,2019-01-01,04:00:00,Winter,Tuesday,0.811667,54.296667,2.628333,0.000000,0.000000,0.000000,0.000000,2323.083333,20144.416667,20219,43.866447,17821.333333
2019-01-01 05:00:00,2019-01-01,05:00:00,Winter,Tuesday,0.681667,53.912833,2.571667,0.000000,0.000000,0.000000,0.000000,2140.416667,20567.666667,20786,157.780822,18427.250000
2019-01-01 06:00:00,2019-01-01,06:00:00,Winter,Tuesday,0.948333,52.255000,2.535000,0.000000,0.000000,0.000000,0.000000,2073.250000,21326.500000,21503,199.544253,19253.250000
2019-01-01 07:00:00,2019-01-01,07:00:00,Winter,Tuesday,2.436667,47.133333,2.866667,44.400000,286.150000,15.016667,1005.750000,1946.333333,21390.000000,21511,102.646791,18437.916667
2019-01-01 08:00:00,2019-01-01,08:00:00,Winter,Tuesday,4.856667,39.211333,3.528333,194.333333,718.666667,39.283333,4952.833333,1963.333333,20820.500000,21134,252.423346,13904.333333
2019-01-01 09:00:00,2019-01-01,09:00:00,Winter,Tuesday,7.046667,32.737500,3.855000,344.983333,824.066667,57.683333,7667.083333,1903.916667,20155.166667,20368,190.610900,10584.166667

In [32]:
print(grid_hourly.index.min(), grid_hourly.index.max())

2019-01-01 00:00:00 2021-12-31 23:00:00

In [33]:
len(grid_hourly)

26304

In [36]:
# Check for any hour that didn't have 5-minute data
missing_hours = grid_hourly['demand_avg_mw'].isna().sum()
print(f"Number of empty hours in grid data: {missing_hours}")

if missing_hours > 0:
    grid_hourly = grid_hourly.interpolate(method='linear')
    print("Gaps filled using linear interpolation.")

Number of empty hours in grid data: 0

In [37]:
# Domain Specific Feature Engineering
import numpy as np

# 1. Cyclical Time Encoding (Crucial for LSTMs)
# This tells the model that Hour 23 is next to Hour 0
grid_hourly['hour_sin'] = np.sin(2 * np.pi * grid_hourly.index.hour / 24)
grid_hourly['hour_cos'] = np.cos(2 * np.pi * grid_hourly.index.hour / 24)

# 2. Momentum (Rolling Changes)
# Is demand ramping up? Positive = Increasing Stress
grid_hourly['demand_ramp'] = grid_hourly['demand_avg_mw'].diff()

# 3. Lag Features (The 'What happened before' context)
# Models love knowing the state of the grid 1 hour and 24 hours ago
grid_hourly['demand_lag_1h'] = grid_hourly['demand_avg_mw'].shift(1)
grid_hourly['net_load_lag_24h'] = grid_hourly['net_load_mw'].shift(24)

# 4. Rolling Averages (Smoothing the noise)
# 3-hour moving average for temperature (to see if buildings are getting heat-soaked)
grid_hourly['temp_rolling_3h'] = grid_hourly['temp_c'].rolling(window=3).mean()

# Since 'diff', 'shift', and 'rolling' create a few NaNs at the very top of the data...
grid_hourly = grid_hourly.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_2764\3298605260.py:23: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_hourly = grid_hourly.fillna(method='bfill')

In [38]:
# 0 = Weekend, 1 = Workday
grid_hourly['is_workday'] = grid_hourly['day_of_week'].isin(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']).astype(int)

In [39]:
# Ratio of actual GHI to a 'perfect' sunny day (approximate max GHI is 1000)
grid_hourly['sky_clearness'] = grid_hourly['ghi_wm2'] / 1000

In [40]:
# Volatility of demand over the last 6 hours
grid_hourly['demand_volatility_6h'] = grid_hourly['demand_avg_mw'].rolling(window=6).std()

In [41]:
# 1. Solar Penetration 
grid_hourly['solar_penetration'] = grid_hourly['solar_gen_mw'] / (grid_hourly['demand_avg_mw'] + 1e-5)

# 2. Wind Penetration
grid_hourly['wind_penetration'] = grid_hourly['wind_gen_mw'] / (grid_hourly['demand_avg_mw'] + 1e-5)

# 3. Total Renewable Penetration (Combined)
# This is the Safety Buffer the grid has at any moment
grid_hourly['total_renewable_penetration'] = (grid_hourly['solar_gen_mw'] + grid_hourly['wind_gen_mw']) / (grid_hourly['demand_avg_mw'] + 1e-5)

In [42]:
# Official NOAA (National Oceanic and Atmospheric Administration) Heat Index Equation.
def calculate_advanced_heat_index(temp_c, humidity):
    T = (temp_c * 9/5) + 32
    R = humidity
    
    # NOAA Regression Constants
    c1, c2, c3 = -42.379, 2.04901523, 10.14333127
    c4, c5, c6 = -0.22475541, -0.00683783, -0.05481717
    c7, c8, c9 = 0.00122874, 0.00085282, -0.00000199
    
    # 3. The Full Power Series
    hi_f = (c1 + (c2 * T) + (c3 * R) + (c4 * T * R) + (c5 * T**2) + 
            (c6 * R**2) + (c7 * T**2 * R) + (c8 * T * R**2) + (c9 * T**2 * R**2))
    
    return (hi_f - 32) * 5/9

grid_hourly['heat_index_c'] = calculate_advanced_heat_index(grid_hourly['temp_c'], grid_hourly['humidity_pct'])

In [43]:
grid_hourly.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c'],
      dtype='object')

In [44]:
# Demand & Net Load Lags 
grid_hourly['demand_lag_24h'] = grid_hourly['demand_avg_mw'].shift(24)
grid_hourly['demand_lag_168h'] = grid_hourly['demand_avg_mw'].shift(168) # 1 Week
grid_hourly['net_load_lag_1h'] = grid_hourly['net_load_mw'].shift(1)

# Temperature Lags - For Heat Waves
grid_hourly['temp_lag_24h'] = grid_hourly['temp_c'].shift(24)
grid_hourly['temp_lag_48h'] = grid_hourly['temp_c'].shift(48)

# Renewable Lags
grid_hourly['solar_gen_lag_24h'] = grid_hourly['solar_gen_mw'].shift(24)
grid_hourly['wind_gen_lag_24h'] = grid_hourly['wind_gen_mw'].shift(24)

# Because a 168h shift creates 168 NaN rows at the very start...
grid_hourly = grid_hourly.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_2764\1364977639.py:15: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_hourly = grid_hourly.fillna(method='bfill')

In [45]:
# 1. Rolling Features 
grid_hourly['demand_rolling_mean_7d'] = grid_hourly['demand_avg_mw'].rolling(window=168).mean()
grid_hourly['demand_rolling_std_7d']  = grid_hourly['demand_avg_mw'].rolling(window=168).std()
grid_hourly['demand_rolling_max_24h'] = grid_hourly['demand_avg_mw'].rolling(window=24).max()

grid_hourly['temp_rolling_mean_7d']   = grid_hourly['temp_c'].rolling(window=168).mean()
grid_hourly['temp_rolling_max_3d']    = grid_hourly['temp_c'].rolling(window=72).max()

grid_hourly['solar_rolling_mean_7d']  = grid_hourly['solar_gen_mw'].rolling(window=168).mean()
grid_hourly['wind_rolling_std_24h']   = grid_hourly['wind_gen_mw'].rolling(window=24).std()

# 2. Degree Days (Physics of HVAC load)
# 18.3°C is the standard Balance Point for buildings
grid_hourly['cooling_degree_hours'] = (grid_hourly['temp_c'] - 18.3).clip(lower=0)
grid_hourly['heating_degree_hours'] = (18.3 - grid_hourly['temp_c']).clip(lower=0)

# 3. Accumulated Heat (The Heatwave Effect)
# This explains why the grid fails on the 3rd day of a heatwave even if temp is the same
grid_hourly['cooling_dh_cumsum_7d'] = grid_hourly['cooling_degree_hours'].rolling(window=168).sum()

# 4. Percentile Ranks 
# pct=True gives a 0-1 scale. 
grid_hourly['demand_percentile_rank'] = grid_hourly['demand_avg_mw'].rank(pct=True)
grid_hourly['temp_percentile_rank']   = grid_hourly['temp_c'].rank(pct=True)

# 5. Extreme Indicators 
demand_95th = grid_hourly['demand_avg_mw'].quantile(0.95)
temp_90th   = grid_hourly['temp_c'].quantile(0.90)

grid_hourly['is_extreme_demand'] = (grid_hourly['demand_avg_mw'] > demand_95th).astype(int)
grid_hourly['is_extreme_temp']   = (grid_hourly['temp_c'] > temp_90th).astype(int)

grid_hourly = grid_hourly.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_2764\857305996.py:33: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_hourly = grid_hourly.fillna(method='bfill')

In [46]:
grid_hourly.shape

(26304, 50)

In [47]:
# Low Renewable + High Demand - Dark Doldrums Indicator
demand_median = grid_hourly['demand_avg_mw'].median()
grid_hourly['low_ren_high_dem'] = ((grid_hourly['total_renewable_penetration'] < 0.2) & 
                                   (grid_hourly['demand_avg_mw'] > demand_median)).astype(int)

In [48]:
grid_hourly.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c', 'demand_lag_24h',
       'demand_lag_168h', 'net_load_lag_1h', 'temp_lag_24h', 'temp_lag_48h',
       'solar_gen_lag_24h', 'wind_gen_lag_24h', 'demand_rolling_mean_7d',
       'demand_rolling_std_7d', 'demand_rolling_max_24h',
       'temp_rolling_mean_7d', 'temp_rolling_max_3d', 'solar_rolling_mean_7d',
       'wind_rolling_std_24h', 'cooling_degree_hours', 'heating_degree_hours',
       'cooling_dh_cumsum_7d', 'demand_percentile_rank',
       'temp_percentile_rank', 'is_extreme_demand', 'is_extreme_temp',
       'low_ren_high_dem'],
      dtype='object')

In [49]:
# 1. Momentum / Ramps
grid_hourly['net_load_ramp'] = grid_hourly['net_load_mw'].diff()
grid_hourly['solar_ramp'] = grid_hourly['solar_gen_mw'].diff()

# 2. Advanced Cyclical Time (Month and Day of Year)
grid_hourly['month'] = grid_hourly.index.month
grid_hourly['month_sin'] = np.sin(2 * np.pi * grid_hourly['month']/12)
grid_hourly['month_cos'] = np.cos(2 * np.pi * grid_hourly['month']/12)

grid_hourly['doy'] = grid_hourly.index.dayofyear
grid_hourly['doy_sin'] = np.sin(2 * np.pi * grid_hourly['doy']/365)
grid_hourly['doy_cos'] = np.cos(2 * np.pi * grid_hourly['doy']/365)

# 3. Stress Accumulation - for rolling count of Heat Wave days
is_hot = (grid_hourly['temp_c'] > 32).astype(int)
grid_hourly['heatwave_index'] = is_hot.rolling(window=72).sum() # Sum of hot hours in last 3 days

# 4. Weekends
grid_hourly['is_weekend'] = (grid_hourly.index.dayofweek >= 5).astype(int)
grid_hourly['is_peak_hour'] = grid_hourly.index.hour.isin([17, 18, 19, 20]).astype(int)

grid_hourly = grid_hourly.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_2764\547228511.py:22: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_hourly = grid_hourly.fillna(method='bfill')

In [52]:
import holidays

regional_holidays = holidays.US(years=[2019, 2020, 2021])
grid_hourly['is_holiday'] = grid_hourly.index.map(lambda x: 1 if x in regional_holidays else 0)
grid_hourly['holiday_name'] = grid_hourly.index.map(lambda x: regional_holidays.get(x))
grid_hourly['is_pre_holiday'] = grid_hourly['is_holiday'].shift(-24).fillna(0)
grid_hourly['is_post_holiday'] = grid_hourly['is_holiday'].shift(24).fillna(0)

In [51]:
pip install holidays

Collecting holidays
  Downloading holidays-0.91-py3-none-any.whl.metadata (50 kB)
Requirement already satisfied: python-dateutil<3,>=2.9.0.post0 in c:\users\hp\anaconda3\lib\site-packages (from holidays) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil<3,>=2.9.0.post0->holidays) (1.17.0)
Downloading holidays-0.91-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 394.6 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 394.6 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 394.6 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 394.6 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 394.6 kB/s eta 0:00:03
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ---------------------- ----------------- 0.8/1.4 MB 314.8 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 255.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 255.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 255.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 255.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 255.2 kB/s eta 0:00:02
   -------------------------------------- - 1.3/1.4 MB 247.5 kB/s eta 0:00:01
   -------------------------------------- - 1.3/1.4 MB 247.5 kB/s eta 0:00:01
   -------------------------------------- - 1.3/1.4 MB 247.5 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 229.9 kB/s eta 0:00:00
Installing collected packages: holidays
Successfully installed holidays-0.91
Note: you may need to restart the kernel to use updated packages.

In [53]:
grid_hourly.shape

(26304, 66)

In [54]:
grid_hourly.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c', 'demand_lag_24h',
       'demand_lag_168h', 'net_load_lag_1h', 'temp_lag_24h', 'temp_lag_48h',
       'solar_gen_lag_24h', 'wind_gen_lag_24h', 'demand_rolling_mean_7d',
       'demand_rolling_std_7d', 'demand_rolling_max_24h',
       'temp_rolling_mean_7d', 'temp_rolling_max_3d', 'solar_rolling_mean_7d',
       'wind_rolling_std_24h', 'cooling_degree_hours', 'heating_degree_hours',
       'cooling_dh_cumsum_7d', 'demand_percentile_rank',
       'temp_percentile_rank', 'is_extreme_demand', 'is_extreme_temp',
       'low_ren_high_dem', 'net_load_ramp', 'solar_ramp', 'month', 'month_sin',
       'month_cos', 'doy', 'doy_sin', 'doy_cos', 'heatwave_index',
       'is_weekend', 'is_peak_hour', 'is_holiday', 'holiday_name',
       'is_pre_holiday', 'is_post_holiday'],
      dtype='object')

In [55]:
target = 'net_load_mw'
metadata = ['date', 'clock_time', 'holiday_name']
features = [col for col in grid_hourly.columns if col not in metadata + [target]]
final_column_order = metadata + features + [target]
grid_hourly = grid_hourly[final_column_order]

In [56]:
grid_hourly.head()

,date,clock_time,holiday_name,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_wm2,dni_wm2,...,doy,doy_sin,doy_cos,heatwave_index,is_weekend,is_peak_hour,is_holiday,is_pre_holiday,is_post_holiday,net_load_mw
timestamp,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,2019-01-01,00:00:00,New Year's Day,Winter,Tuesday,1.683333,55.809333,2.838333,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,0.0,0.0,19039.333333
2019-01-01 01:00:00,2019-01-01,01:00:00,New Year's Day,Winter,Tuesday,1.405000,55.159000,2.770000,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,0.0,0.0,18600.166667
2019-01-01 02:00:00,2019-01-01,02:00:00,New Year's Day,Winter,Tuesday,1.186667,54.532833,2.690000,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,0.0,0.0,18108.333333
2019-01-01 03:00:00,2019-01-01,03:00:00,New Year's Day,Winter,Tuesday,0.985000,54.317833,2.655000,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,0.0,0.0,17778.166667
2019-01-01 04:00:00,2019-01-01,04:00:00,New Year's Day,Winter,Tuesday,0.811667,54.296667,2.628333,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,0.0,0.0,17821.333333

In [58]:
grid_hourly.isna().sum()

date                   0
clock_time             0
holiday_name       25440
season                 0
day_of_week            0
                   ...
is_peak_hour           0
is_holiday             0
is_pre_holiday         0
is_post_holiday        0
net_load_mw            0
Length: 66, dtype: int64

In [59]:
grid_hourly['holiday_name'] = grid_hourly['holiday_name'].fillna('No Holiday')

print(f"Remaining NaNs in holiday_name: {grid_hourly['holiday_name'].isna().sum()}")

Remaining NaNs in holiday_name: 0

In [60]:
# Save the final preprocessed dataset
grid_hourly.to_csv('Grid_Data_Final_Preprocessed.csv', index=False)