In [1]:
import pandas as pd
grid_data = pd.read_csv(r"C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Multi Scale Energy Stress Analysis\data\ca_grid_dataset.csv")
grid_data.head()

,Unnamed: 0,Time,Season,Day_of_the_week,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand
0,0,2019-01-01-T00:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216
1,1,2019-01-01-T00:05,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106
2,2,2019-01-01-T00:10,1,1,0.0,0.0,0.0,2.88,56.194,1.78,0,2916,22130
3,3,2019-01-01-T00:15,1,1,0.0,0.0,0.0,2.88,56.344,1.74,0,2920,22040
4,4,2019-01-01-T00:20,1,1,0.0,0.0,0.0,2.84,56.440,1.72,0,2902,21963

In [2]:
grid_data.columns

Index(['Unnamed: 0', 'Time', 'Season', 'Day_of_the_week', 'DHI', 'DNI', 'GHI',
       'Wind_speed', 'Humidity', 'Temperature', 'PV_production',
       'Wind_production', 'Electric_demand'],
      dtype='object')

In [3]:
if 'Unnamed: 0' in grid_data.columns:
    grid_data = grid_data.drop(columns=['Unnamed: 0'])

In [4]:
#Separate Date and Time
grid_data['Time'] = pd.to_datetime(grid_data['Time'], format='%Y-%m-%d-T%H:%M')
grid_data['Date'] = grid_data['Time'].dt.date
grid_data['Clock_Time'] = grid_data['Time'].dt.time

In [5]:
grid_data.head(2)

,Time,Season,Day_of_the_week,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand,Date,Clock_Time
0,2019-01-01 00:00:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216,2019-01-01,00:00:00
1,2019-01-01 00:05:00,1,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106,2019-01-01,00:05:00

In [6]:
season_map = {1: 'Winter', 2: 'Spring', 3: 'Summer', 4: 'Autumn'}
grid_data['Season_Name'] = grid_data['Season'].map(season_map)
grid_data['Day_Name'] = grid_data['Time'].dt.day_name()
grid_data = grid_data.drop(columns=['Day_of_the_week'], errors='ignore')

In [7]:
grid_data.head(3)

,Time,Season,DHI,DNI,GHI,Wind_speed,Humidity,Temperature,PV_production,Wind_production,Electric_demand,Date,Clock_Time,Season_Name,Day_Name
0,2019-01-01 00:00:00,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2810,22216,2019-01-01,00:00:00,Winter,Tuesday
1,2019-01-01 00:05:00,1,0.0,0.0,0.0,2.88,56.036,1.82,0,2862,22106,2019-01-01,00:05:00,Winter,Tuesday
2,2019-01-01 00:10:00,1,0.0,0.0,0.0,2.88,56.194,1.78,0,2916,22130,2019-01-01,00:10:00,Winter,Tuesday

In [8]:
#Renaming columns
new_names = {
    'Time': 'timestamp',
    'Date': 'date',
    'Clock_Time': 'clock_time',
    'Season_Name': 'season',
    'Day_Name': 'day_of_week',
    'DHI': 'dhi_w_per_m2',
    'DNI': 'dni_w_per_m2',
    'GHI': 'ghi_w_per_m2',
    'Wind_speed': 'wind_speed_ms',
    'Humidity': 'humidity_pct',
    'Temperature': 'temp_c',
    'PV_production': 'solar_energy_generation_mw',
    'Wind_production': 'wind_energy_generation_mw',
    'Electric_demand': 'electric_demand_mw'
}

grid_data = grid_data.rename(columns=new_names)

ordered_cols = [
    'timestamp', 'date', 'clock_time', 'season', 'day_of_week', 
    'temp_c', 'humidity_pct', 'wind_speed_ms', 'ghi_w_per_m2', 'dni_w_per_m2', 'dhi_w_per_m2',
    'solar_energy_generation_mw', 'wind_energy_generation_mw', 'electric_demand_mw'
]

grid_data = grid_data[ordered_cols]

In [9]:
grid_data.head(3)

,timestamp,date,clock_time,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_w_per_m2,dni_w_per_m2,dhi_w_per_m2,solar_energy_generation_mw,wind_energy_generation_mw,electric_demand_mw
0,2019-01-01 00:00:00,2019-01-01,00:00:00,Winter,Tuesday,1.82,56.036,2.88,0.0,0.0,0.0,0,2810,22216
1,2019-01-01 00:05:00,2019-01-01,00:05:00,Winter,Tuesday,1.82,56.036,2.88,0.0,0.0,0.0,0,2862,22106
2,2019-01-01 00:10:00,2019-01-01,00:10:00,Winter,Tuesday,1.78,56.194,2.88,0.0,0.0,0.0,0,2916,22130

In [10]:
#Data Validation
print("Missing values per column:")
print(grid_data.isnull().sum())

Missing values per column:
timestamp                     0
date                          0
clock_time                    0
season                        0
day_of_week                   0
temp_c                        0
humidity_pct                  0
wind_speed_ms                 0
ghi_w_per_m2                  0
dni_w_per_m2                  0
dhi_w_per_m2                  0
solar_energy_generation_mw    0
wind_energy_generation_mw     0
electric_demand_mw            0
dtype: int64

In [11]:
# Check for negatives
negatives = (grid_data[['solar_energy_generation_mw', 'wind_energy_generation_mw', 'electric_demand_mw']] < 0).sum()
print("Negative values found:\n", negatives)

Negative values found:
 solar_energy_generation_mw    112829
wind_energy_generation_mw        216
electric_demand_mw                 0
dtype: int64

In [12]:
# Check when these negatives happen
neg_solar_hours = grid_data[grid_data['solar_energy_generation_mw'] < 0]['clock_time'].value_counts()
print("Hours where solar is negative:")
print(neg_solar_hours)

Hours where solar is negative:
clock_time
03:05:00    814
03:35:00    813
03:40:00    813
03:25:00    813
03:30:00    813
           ...
16:35:00     11
07:15:00      5
16:30:00      4
16:25:00      2
16:20:00      1
Name: count, Length: 180, dtype: int64

In [13]:
print("\nSummary of negative solar values:")
print(grid_data[grid_data['solar_energy_generation_mw'] < 0]['solar_energy_generation_mw'].describe())

Summary of negative solar values:
count    112829.000000
mean        -34.561770
std          11.034527
min        -145.000000
25%         -41.000000
50%         -38.000000
75%         -31.000000
max          -1.000000
Name: solar_energy_generation_mw, dtype: float64

In [14]:
# Dealing with negatives
grid_data['sun_is_up'] = grid_data['ghi_w_per_m2'] > 5

night_mask = (grid_data['sun_is_up'] == False) & (grid_data['solar_energy_generation_mw'] < 0)
day_mask = (grid_data['sun_is_up'] == True) & (grid_data['solar_energy_generation_mw'] < 0)

grid_data.loc[night_mask, 'solar_energy_generation_mw'] = 0
grid_data.loc[day_mask, 'solar_energy_generation_mw'] = grid_data.loc[day_mask, 'solar_energy_generation_mw'].abs()

grid_data['solar_energy_generation_mw'] = grid_data['solar_energy_generation_mw'].clip(lower=0)

print(f"Fixed {night_mask.sum()} night-time rows to zero.")
print(f"Fixed {day_mask.sum()} day-time rows using modulus.")

Fixed 106888 night-time rows to zero.
Fixed 5941 day-time rows using modulus.

In [15]:
# Dealing with wind negatives
grid_data['wind_is_blowing'] = grid_data['wind_speed_ms'] > 2.5

wind_noise_mask = (grid_data['wind_is_blowing'] == False) & (grid_data['wind_energy_generation_mw'] < 0)
wind_sign_error_mask = (grid_data['wind_is_blowing'] == True) & (grid_data['wind_energy_generation_mw'] < 0)

grid_data.loc[wind_noise_mask, 'wind_energy_generation_mw'] = 0
grid_data.loc[wind_sign_error_mask, 'wind_energy_generation_mw'] = grid_data.loc[wind_sign_error_mask, 'wind_energy_generation_mw'].abs()

grid_data['wind_energy_generation_mw'] = grid_data['wind_energy_generation_mw'].clip(lower=0)

print(f"Fixed {wind_noise_mask.sum()} low-wind noise rows.")
print(f"Fixed {wind_sign_error_mask.sum()} wind sign-error rows.")

Fixed 110 low-wind noise rows.
Fixed 106 wind sign-error rows.

In [16]:
# Check for temperature outliers 
temp_outliers = grid_data[(grid_data['temp_c'] < -10) | (grid_data['temp_c'] > 55)]
print(f"Strange temperature rows: {len(temp_outliers)}")

Strange temperature rows: 0

In [17]:
# Force solar to zero at night (when GHI is 0)
grid_data.loc[grid_data['ghi_w_per_m2'] <= 0, 'solar_energy_generation_mw'] = 0

In [18]:
# Check if every day has 288 rows (12 rows/hr * 24 hrs)
counts = grid_data.groupby('date').size()
incomplete_days = counts[counts != 288]
print("Days with missing 5-minute intervals:\n", incomplete_days)

Days with missing 5-minute intervals:
 Series([], dtype: int64)

In [19]:
print(grid_data[grid_data['sun_is_up'] == True]['solar_energy_generation_mw'].max())

13191

In [20]:
# 'Real' solar data left
active_solar_count = (grid_data['solar_energy_generation_mw'] > 0).sum()
total_rows = len(grid_data)
percentage_active = (active_solar_count / total_rows) * 100

print(f"Rows with active solar production: {active_solar_count}")
print(f"Percentage of total data: {percentage_active:.2f}%")

Rows with active solar production: 160626
Percentage of total data: 50.89%

In [21]:
# Resampling to 15 minutes

if grid_data.index.name != 'timestamp':
    grid_data = grid_data.set_index('timestamp')

# Create the complete 15 minutes dataset
grid_15min = grid_data.resample('15min').agg({
    'date': 'first',
    'clock_time': 'first',
    'season': 'first',      
    'day_of_week': 'first',
    'temp_c': 'mean',
    'humidity_pct': 'mean',
    'wind_speed_ms': 'mean',
    'ghi_w_per_m2': 'mean',
    'dni_w_per_m2': 'mean',
    'dhi_w_per_m2': 'mean',
    'solar_energy_generation_mw': 'mean',
    'wind_energy_generation_mw': 'mean',
    'electric_demand_mw': ['mean', 'max', 'std'] # Keep the 'spikiness' metrics
}).copy()

grid_15min.columns = [
    'date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct', 'wind_speed_ms', 
    'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw', 'wind_gen_mw', 
    'demand_avg_mw', 'demand_max_mw', 'demand_std_mw'
]

# Calculate Net Load
grid_15min['net_load_mw'] = grid_15min['demand_avg_mw'] - grid_15min['solar_gen_mw'] - grid_15min['wind_gen_mw']

In [22]:
grid_15min.head(10)

,date,clock_time,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_wm2,dni_wm2,dhi_wm2,solar_gen_mw,wind_gen_mw,demand_avg_mw,demand_max_mw,demand_std_mw,net_load_mw
timestamp,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,2019-01-01,00:00:00,Winter,Tuesday,1.806667,56.088667,2.880000,0.0,0.0,0.0,0.0,2862.666667,22150.666667,22216,57.838857,19288.000000
2019-01-01 00:15:00,2019-01-01,00:15:00,Winter,Tuesday,1.713333,56.454000,2.846667,0.0,0.0,0.0,0.0,2898.666667,21956.666667,22040,86.673718,19058.000000
2019-01-01 00:30:00,2019-01-01,00:30:00,Winter,Tuesday,1.653333,55.471333,2.820000,0.0,0.0,0.0,0.0,2805.000000,21729.666667,21792,63.010581,18924.666667
2019-01-01 00:45:00,2019-01-01,00:45:00,Winter,Tuesday,1.560000,55.223333,2.806667,0.0,0.0,0.0,0.0,2682.000000,21568.666667,21624,56.536124,18886.666667
2019-01-01 01:00:00,2019-01-01,01:00:00,Winter,Tuesday,1.486667,55.520000,2.793333,0.0,0.0,0.0,0.0,2521.666667,21369.000000,21435,66.000000,18847.333333
2019-01-01 01:15:00,2019-01-01,01:15:00,Winter,Tuesday,1.433333,55.740667,2.773333,0.0,0.0,0.0,0.0,2496.000000,21184.666667,21247,62.002688,18688.666667
2019-01-01 01:30:00,2019-01-01,01:30:00,Winter,Tuesday,1.386667,54.823333,2.766667,0.0,0.0,0.0,0.0,2511.000000,21009.000000,21063,54.000000,18498.000000
2019-01-01 01:45:00,2019-01-01,01:45:00,Winter,Tuesday,1.313333,54.552000,2.746667,0.0,0.0,0.0,0.0,2469.333333,20836.000000,20897,60.506198,18366.666667
2019-01-01 02:00:00,2019-01-01,02:00:00,Winter,Tuesday,1.273333,54.702667,2.713333,0.0,0.0,0.0,0.0,2370.000000,20675.333333,20724,49.003401,18305.333333
2019-01-01 02:15:00,2019-01-01,02:15:00,Winter,Tuesday,1.213333,54.944667,2.680000,0.0,0.0,0.0,0.0,2382.000000,20543.666667,20594,48.169838,18161.666667

In [23]:
print(grid_15min.index.min(), grid_15min.index.max())

2019-01-01 00:00:00 2021-12-31 23:45:00

In [24]:
len(grid_15min)

105216

In [25]:
# Check for any hour that didn't have 5-minute data
missing_hours = grid_15min['demand_avg_mw'].isna().sum()
print(f"Number of empty hours in grid data: {missing_hours}")

if missing_hours > 0:
    grid_15min = grid_15min.interpolate(method='linear')
    print("Gaps filled using linear interpolation.")

Number of empty hours in grid data: 0

In [26]:
# Domain Specific Feature Engineering
import numpy as np

# 1. Cyclical Time Encoding (Crucial for LSTMs)
# This tells the model that Hour 23 is next to Hour 0
grid_15min['hour_sin'] = np.sin(2 * np.pi * grid_15min.index.hour / 24)
grid_15min['hour_cos'] = np.cos(2 * np.pi * grid_15min.index.hour / 24)

# 2. Momentum (Rolling Changes)
# Is demand ramping up? Positive = Increasing Stress
grid_15min['demand_ramp'] = grid_15min['demand_avg_mw'].diff()

# 3. Lag Features (The 'What happened before' context)
# Models love knowing the state of the grid 1 hour and 24 hours ago
grid_15min['demand_lag_1h'] = grid_15min['demand_avg_mw'].shift(1)
grid_15min['net_load_lag_24h'] = grid_15min['net_load_mw'].shift(24)

# 4. Rolling Averages (Smoothing the noise)
# 3-hour moving average for temperature (to see if buildings are getting heat-soaked)
grid_15min['temp_rolling_3h'] = grid_15min['temp_c'].rolling(window=3).mean()

# Since 'diff', 'shift', and 'rolling' create a few NaNs at the very top of the data...
grid_15min = grid_15min.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_37360\2296641898.py:23: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_15min = grid_15min.fillna(method='bfill')

In [27]:
# 0 = Weekend, 1 = Workday
grid_15min['is_workday'] = grid_15min['day_of_week'].isin(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']).astype(int)

In [28]:
# Ratio of actual GHI to a 'perfect' sunny day (approximate max GHI is 1000)
grid_15min['sky_clearness'] = grid_15min['ghi_wm2'] / 1000

In [29]:
# Volatility of demand over the last 6 hours
grid_15min['demand_volatility_6h'] = grid_15min['demand_avg_mw'].rolling(window=6).std()

In [30]:
# 1. Solar Penetration 
grid_15min['solar_penetration'] = grid_15min['solar_gen_mw'] / (grid_15min['demand_avg_mw'] + 1e-5)

# 2. Wind Penetration
grid_15min['wind_penetration'] = grid_15min['wind_gen_mw'] / (grid_15min['demand_avg_mw'] + 1e-5)

# 3. Total Renewable Penetration (Combined)
# This is the Safety Buffer the grid has at any moment
grid_15min['total_renewable_penetration'] = (grid_15min['solar_gen_mw'] + grid_15min['wind_gen_mw']) / (grid_15min['demand_avg_mw'] + 1e-5)

In [31]:
# Official NOAA (National Oceanic and Atmospheric Administration) Heat Index Equation.
def calculate_advanced_heat_index(temp_c, humidity):
    T = (temp_c * 9/5) + 32
    R = humidity
    
    # NOAA Regression Constants
    c1, c2, c3 = -42.379, 2.04901523, 10.14333127
    c4, c5, c6 = -0.22475541, -0.00683783, -0.05481717
    c7, c8, c9 = 0.00122874, 0.00085282, -0.00000199
    
    # 3. The Full Power Series
    hi_f = (c1 + (c2 * T) + (c3 * R) + (c4 * T * R) + (c5 * T**2) + 
            (c6 * R**2) + (c7 * T**2 * R) + (c8 * T * R**2) + (c9 * T**2 * R**2))
    
    return (hi_f - 32) * 5/9

grid_15min['heat_index_c'] = calculate_advanced_heat_index(grid_15min['temp_c'], grid_15min['humidity_pct'])

In [32]:
grid_15min.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c'],
      dtype='object')

In [33]:
# Demand & Net Load Lags 
grid_15min['demand_lag_24h'] = grid_15min['demand_avg_mw'].shift(24)
grid_15min['demand_lag_168h'] = grid_15min['demand_avg_mw'].shift(168) # 1 Week
grid_15min['net_load_lag_1h'] = grid_15min['net_load_mw'].shift(1)

# Temperature Lags - For Heat Waves
grid_15min['temp_lag_24h'] = grid_15min['temp_c'].shift(24)
grid_15min['temp_lag_48h'] = grid_15min['temp_c'].shift(48)

# Renewable Lags
grid_15min['solar_gen_lag_24h'] = grid_15min['solar_gen_mw'].shift(24)
grid_15min['wind_gen_lag_24h'] = grid_15min['wind_gen_mw'].shift(24)

# Because a 168h shift creates 168 NaN rows at the very start...
grid_15min = grid_15min.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_37360\1484300785.py:15: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_15min = grid_15min.fillna(method='bfill')

In [34]:
# 1. Rolling Features 
grid_15min['demand_rolling_mean_7d'] = grid_15min['demand_avg_mw'].rolling(window=168).mean()
grid_15min['demand_rolling_std_7d']  = grid_15min['demand_avg_mw'].rolling(window=168).std()
grid_15min['demand_rolling_max_24h'] = grid_15min['demand_avg_mw'].rolling(window=24).max()

grid_15min['temp_rolling_mean_7d']   = grid_15min['temp_c'].rolling(window=168).mean()
grid_15min['temp_rolling_max_3d']    = grid_15min['temp_c'].rolling(window=72).max()

grid_15min['solar_rolling_mean_7d']  = grid_15min['solar_gen_mw'].rolling(window=168).mean()
grid_15min['wind_rolling_std_24h']   = grid_15min['wind_gen_mw'].rolling(window=24).std()

# 2. Degree Days (Physics of HVAC load)
# 18.3°C is the standard Balance Point for buildings
grid_15min['cooling_degree_hours'] = (grid_15min['temp_c'] - 18.3).clip(lower=0)
grid_15min['heating_degree_hours'] = (18.3 - grid_15min['temp_c']).clip(lower=0)

# 3. Accumulated Heat (The Heatwave Effect)
# This explains why the grid fails on the 3rd day of a heatwave even if temp is the same
grid_15min['cooling_dh_cumsum_7d'] = grid_15min['cooling_degree_hours'].rolling(window=168).sum()

# 4. Percentile Ranks 
# pct=True gives a 0-1 scale. 
grid_15min['demand_percentile_rank'] = grid_15min['demand_avg_mw'].rank(pct=True)
grid_15min['temp_percentile_rank']   = grid_15min['temp_c'].rank(pct=True)

# 5. Extreme Indicators 
demand_95th = grid_15min['demand_avg_mw'].quantile(0.95)
temp_90th   = grid_15min['temp_c'].quantile(0.90)

grid_15min['is_extreme_demand'] = (grid_15min['demand_avg_mw'] > demand_95th).astype(int)
grid_15min['is_extreme_temp']   = (grid_15min['temp_c'] > temp_90th).astype(int)

grid_15min = grid_15min.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_37360\717322561.py:33: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_15min = grid_15min.fillna(method='bfill')

In [35]:
grid_15min.shape

(105216, 50)

In [36]:
# Low Renewable + High Demand - Dark Doldrums Indicator
demand_median = grid_15min['demand_avg_mw'].median()
grid_15min['low_ren_high_dem'] = ((grid_15min['total_renewable_penetration'] < 0.2) & 
                                   (grid_15min['demand_avg_mw'] > demand_median)).astype(int)

In [37]:
grid_15min.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c', 'demand_lag_24h',
       'demand_lag_168h', 'net_load_lag_1h', 'temp_lag_24h', 'temp_lag_48h',
       'solar_gen_lag_24h', 'wind_gen_lag_24h', 'demand_rolling_mean_7d',
       'demand_rolling_std_7d', 'demand_rolling_max_24h',
       'temp_rolling_mean_7d', 'temp_rolling_max_3d', 'solar_rolling_mean_7d',
       'wind_rolling_std_24h', 'cooling_degree_hours', 'heating_degree_hours',
       'cooling_dh_cumsum_7d', 'demand_percentile_rank',
       'temp_percentile_rank', 'is_extreme_demand', 'is_extreme_temp',
       'low_ren_high_dem'],
      dtype='object')

In [38]:
# 1. Momentum / Ramps
grid_15min['net_load_ramp'] = grid_15min['net_load_mw'].diff()
grid_15min['solar_ramp'] = grid_15min['solar_gen_mw'].diff()
grid_15min['wind_ramp'] = grid_15min['wind_gen_mw'] - grid_15min['wind_gen_mw'].shift(1)
grid_15min['renewable_ramp'] = (grid_15min['solar_gen_mw'] + grid_15min['wind_gen_mw']) -(grid_15min['solar_gen_mw'].shift(1) + grid_15min['wind_gen_mw'].shift(1))

# 2. Advanced Cyclical Time (Month and Day of Year)
grid_15min['month'] = grid_15min.index.month
grid_15min['month_sin'] = np.sin(2 * np.pi * grid_15min['month']/12)
grid_15min['month_cos'] = np.cos(2 * np.pi * grid_15min['month']/12)

grid_15min['doy'] = grid_15min.index.dayofyear
grid_15min['doy_sin'] = np.sin(2 * np.pi * grid_15min['doy']/365)
grid_15min['doy_cos'] = np.cos(2 * np.pi * grid_15min['doy']/365)

# 3. Stress Accumulation - for rolling count of Heat Wave days
is_hot = (grid_15min['temp_c'] > 32).astype(int)
grid_15min['heatwave_index'] = is_hot.rolling(window=72).sum() # Sum of hot hours in last 3 days

# 4. Weekends
grid_15min['is_weekend'] = (grid_15min.index.dayofweek >= 5).astype(int)
grid_15min['is_peak_hour'] = grid_15min.index.hour.isin([17, 18, 19, 20]).astype(int)

grid_15min = grid_15min.fillna(method='bfill')

C:\Users\Hp\AppData\Local\Temp\ipykernel_37360\3426437604.py:24: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grid_15min = grid_15min.fillna(method='bfill')

In [39]:
import holidays

regional_holidays = holidays.US(years=[2019, 2020, 2021])
grid_15min['is_holiday'] = grid_15min.index.map(lambda x: 1 if x in regional_holidays else 0)
grid_15min['holiday_name'] = grid_15min.index.map(lambda x: regional_holidays.get(x))
grid_15min['is_pre_holiday'] = grid_15min['is_holiday'].shift(-24).fillna(0)
grid_15min['is_post_holiday'] = grid_15min['is_holiday'].shift(24).fillna(0)

In [40]:
grid_15min.shape

(105216, 68)

In [41]:
grid_15min.columns

Index(['date', 'clock_time', 'season', 'day_of_week', 'temp_c', 'humidity_pct',
       'wind_speed_ms', 'ghi_wm2', 'dni_wm2', 'dhi_wm2', 'solar_gen_mw',
       'wind_gen_mw', 'demand_avg_mw', 'demand_max_mw', 'demand_std_mw',
       'net_load_mw', 'hour_sin', 'hour_cos', 'demand_ramp', 'demand_lag_1h',
       'net_load_lag_24h', 'temp_rolling_3h', 'is_workday', 'sky_clearness',
       'demand_volatility_6h', 'solar_penetration', 'wind_penetration',
       'total_renewable_penetration', 'heat_index_c', 'demand_lag_24h',
       'demand_lag_168h', 'net_load_lag_1h', 'temp_lag_24h', 'temp_lag_48h',
       'solar_gen_lag_24h', 'wind_gen_lag_24h', 'demand_rolling_mean_7d',
       'demand_rolling_std_7d', 'demand_rolling_max_24h',
       'temp_rolling_mean_7d', 'temp_rolling_max_3d', 'solar_rolling_mean_7d',
       'wind_rolling_std_24h', 'cooling_degree_hours', 'heating_degree_hours',
       'cooling_dh_cumsum_7d', 'demand_percentile_rank',
       'temp_percentile_rank', 'is_extreme_demand', 'is_extreme_temp',
       'low_ren_high_dem', 'net_load_ramp', 'solar_ramp', 'wind_ramp',
       'renewable_ramp', 'month', 'month_sin', 'month_cos', 'doy', 'doy_sin',
       'doy_cos', 'heatwave_index', 'is_weekend', 'is_peak_hour', 'is_holiday',
       'holiday_name', 'is_pre_holiday', 'is_post_holiday'],
      dtype='object')

In [42]:
target = 'net_load_mw'
metadata = ['date', 'clock_time', 'holiday_name']
features = [col for col in grid_15min.columns if col not in metadata + [target]]
final_column_order = metadata + features + [target]
grid_15min = grid_15min[final_column_order]

In [43]:
grid_15min.head()

,date,clock_time,holiday_name,season,day_of_week,temp_c,humidity_pct,wind_speed_ms,ghi_wm2,dni_wm2,...,doy,doy_sin,doy_cos,heatwave_index,is_weekend,is_peak_hour,is_holiday,is_pre_holiday,is_post_holiday,net_load_mw
timestamp,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,2019-01-01,00:00:00,New Year's Day,Winter,Tuesday,1.806667,56.088667,2.880000,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,1.0,0.0,19288.000000
2019-01-01 00:15:00,2019-01-01,00:15:00,New Year's Day,Winter,Tuesday,1.713333,56.454000,2.846667,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,1.0,0.0,19058.000000
2019-01-01 00:30:00,2019-01-01,00:30:00,New Year's Day,Winter,Tuesday,1.653333,55.471333,2.820000,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,1.0,0.0,18924.666667
2019-01-01 00:45:00,2019-01-01,00:45:00,New Year's Day,Winter,Tuesday,1.560000,55.223333,2.806667,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,1.0,0.0,18886.666667
2019-01-01 01:00:00,2019-01-01,01:00:00,New Year's Day,Winter,Tuesday,1.486667,55.520000,2.793333,0.0,0.0,...,1,0.017213,0.999852,0.0,0,0,1,1.0,0.0,18847.333333

In [44]:
grid_15min.isna().sum()

date                    0
clock_time              0
holiday_name       101760
season                  0
day_of_week             0
                    ...
is_peak_hour            0
is_holiday              0
is_pre_holiday          0
is_post_holiday         0
net_load_mw             0
Length: 68, dtype: int64

In [45]:
grid_15min['holiday_name'] = grid_15min['holiday_name'].fillna('No Holiday')

print(f"Remaining NaNs in holiday_name: {grid_15min['holiday_name'].isna().sum()}")

Remaining NaNs in holiday_name: 0

In [46]:
# Save the final preprocessed dataset
grid_15min.to_csv('grid_data_final_preprocessed_15min.csv', index=False)